### ISSUE TITLE
ERROR: 🧓 Deployer contract is not inited yet, please send some TON there and then I can deploy project

### ISSUE THREAD

**Issue by rocalex** [disintar/toncli#12]
When I try to deploy smart contract on testnet, I meet this message, how to solve it?

**Comment by Nikita757** [comment]
> When I try to deploy smart contract on testnet, I meet this message, how to solve it?

Try to run `toncli addrs`, from it you'll get an address, where you'll need to send some toncoins and a link to Telegram bot, from whom you can get those toncoins (testnet). After sending coins you'll should be able to deploy a contract.

**Comment by rocalex** [comment]
It's resolved, but got new error.

**Comment by tvorogme** [comment]
Please, first deploy contract before interact with it. If you have got this error not in project - please remove `wallet` from `~/.config/toncli` and try to deploy simple wallet one more time.
