### ISSUE TITLE
WARNING: 🤖 Can't find executable for func, please specify it, e.g.: /usr/bin/func

### ISSUE THREAD

**Issue by IcarusRyy** [disintar/toncli#47]

**Comment by IcarusRyy** [comment]
PS D:\TonBinaries> toncli
INFO: 🥰 First time run - i'll create config folder 4you and save some stuff there
INFO: 🤖 Check all executables are installed...
ERROR: Command '['D:\\TonBinaries\\func.exe', '-V']' returned non-zero exit status 3221225781.
WARNING: 🤖 Can't find executable for func, please specify it, e.g.: /usr/bin/func
Path:

**Comment by IcarusRyy** [comment]
How to configure func in windows system？ what should i do?

**Comment by tvorogme** [comment]
When you run `D:\TonBinaries\func.exe -V` command what output you receive?

**Comment by IcarusRyy** [comment]
> When you run `D:\TonBinaries\func.exe -V` command what output you receive?

i think need to set lint client。https://ton.org/docs/#/compile
