### ISSUE TITLE
toncli run func/code.func   Error

### ISSUE THREAD

**Issue by IcarusRyy** [disintar/toncli#49]
PS D:\demo\TonDemo-next\wallet> toncli run func/code.func
[ 1][t 0][2022-05-21 01:55:43.5564072][fift-main.cpp:180]       Error interpreting standard preamble file `Fift.fif`: cannot locate file `Fift.fif`
Check that correct include path is set by -I or by FIFTPATH environment variable, or disable standard preamble by -n.

**Comment by tvorogme** [comment]
Hi. To fix this problem on windows - copy all [fift-lib](https://github.com/disintar/toncli/tree/master/src/toncli/lib/fift-libs) content into project root.

Original issue: https://github.com/disintar/toncli/issues/14
