### ISSUE TITLE
broken with latest 4.x.x bitstring

### ISSUE THREAD

**Issue by cloudfwd-artur** [disintar/toncli#96]
### Bug Type

Functional

### Reproduction steps

* use `pip install toncli` to install it
* run it using `toncli` command

### Actual result

it crashes with 
```
    from bitstring import BitString
ImportError: cannot import name 'BitString' from 'bitstring' 
```

### Expected result

it should not crash

### Suggested Severity

Critical

### Device

OS: Fedora

```
pip list | grep bitstr
bitstring          4.0.1
```

### Additional Context

Fix is to downgrade `bitstring` pip module to 3.x.x version 
for example 
`pip install bitstring==3.1.9` fixes the issue

**Comment by tvorogme** [comment]
Hey! Already fixed https://github.com/disintar/toncli/blob/master/requirements.txt#L6 will be released with new version to PyPi in several days.

thanks for issue

**Comment by cloudfwd-artur** [comment]
thank you.

thank you for the great work you are  doing for TON.
